"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['tipitaka.py']
DATA_FILES = ['config',
 'spell_pali',
 'spell_thai',
 'resources']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/sutee/Works/E-Tipitaka.icns',
 'packages': 'whoosh'}

setup(
    name="E-Tipitaka",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

